In [1]:
from __future__ import annotations

import json
import logging
import re
import subprocess
import types
from pathlib import Path

import pandas as pd
import soccerdata as sd
import soccerdata._common as common
import undetected_chromedriver as uc
import yaml
from pymongo import MongoClient

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "dev_scripts" else Path.cwd()
CONFIG_PATH = PROJECT_ROOT / "config" / "config.yaml"
CHROME_PATH = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("season_lineups")

print(PROJECT_ROOT)

[07/25/26 11:51:56] INFO     No custom team name replacements found. You can configure these in       ]8;id=15603616;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=15603617;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/_config.py#92\92]8;;\
                             /Users/mario_omescu/soccerdata/config/teamname_replacements.json.

                    INFO     No custom league dict found. You can configure additional leagues in    ]8;id=15603623;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=15603624;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/_config.py#190\190]8;;\
                             /Users/mario_omescu/soccerdata/config/league_dict.json.

/Users/mario_omescu/Library/Mobile Documents/com~apple~CloudDocs/Sports Analytics/WhoScored Events Data

In [2]:
def get_chrome_major(path: str = CHROME_PATH) -> int:
    out = subprocess.check_output([path, "--version"], text=True)
    match = re.search(r"(\d+)\.", out)
    if not match:
        raise RuntimeError(f"Could not detect Chrome version from: {out}")
    return int(match.group(1))


def patch_soccerdata_chromedriver() -> None:
    def patched_init_webdriver(self):
        chrome_path = str(self.path_to_browser or CHROME_PATH)
        chrome_major = get_chrome_major(chrome_path)

        opts = uc.ChromeOptions()
        opts.add_argument("--no-sandbox")
        opts.add_argument("--disable-dev-shm-usage")
        opts.add_argument("--start-maximized")

        return uc.Chrome(
            options=opts,
            version_main=chrome_major,
            browser_executable_path=chrome_path,
            headless=self.headless,
        )

    common.BaseSeleniumReader._init_webdriver = patched_init_webdriver


def patch_soccerdata_json_loader() -> None:
    def tolerant_json_load(fp, *args, **kwargs):
        content = fp.read()
        if isinstance(content, bytes):
            content = content.decode("utf-8", errors="ignore")

        content = content.strip()
        if content.startswith("<html"):
            start = content.find("{")
            end = content.rfind("}") + 1
            if start != -1 and end > start:
                content = content[start:end]

        return json.loads(content)

    json.load = tolerant_json_load


patch_soccerdata_chromedriver()
patch_soccerdata_json_loader()

print(f"SoccerData notebook patches applied. Chrome major: {get_chrome_major()}")

SoccerData notebook patches applied. Chrome major: 150

In [3]:
with CONFIG_PATH.open("r", encoding="utf-8") as f:
    cfg = yaml.safe_load(f)

season_cfg = cfg["season"]
mongo_cfg = cfg["mongo"]
collections = mongo_cfg["collections"]

SEASON_YEAR = season_cfg["year"]
SEASON_SHORT = season_cfg["year_short"]
LEAGUE = season_cfg["league"]
COMPETITION_NAME = season_cfg["name"]
COMPETITION_COUNTRY = season_cfg["country"]

client = MongoClient(mongo_cfg["url"])
db = client[mongo_cfg["db"]]
collection_teams = db[collections["collection_teams"]]
collection_schedule = db[collections["collection_schedule"]]
collection_lineups = db[collections["collection_lineups"]]

available_teams = pd.DataFrame(collection_teams.find(
    {},
    {'_id':0,'ws_team_id': 1, 'ws_team_name': 1}))
schedule_docs = list(collection_schedule.find(
    {"season": SEASON_YEAR, "game_status": "finished"},
    {"_id": 0},
).sort("game_date", 1))


finished_games = pd.DataFrame(schedule_docs)
if finished_games.empty:
    raise ValueError(f"No finished games found in Mongo for season={SEASON_YEAR}")

finished_games["game_id"] = finished_games["game_id"].astype(int)
display(finished_games[["game_id", "home_team_name", "away_team_name", "week"]].head())
print(f"Finished games: {len(finished_games)}")

   game_id       home_team_name away_team_name  week
0  1643039  Eintracht Frankfurt  Bayern Munich     1
1  1643046             Augsburg       Freiburg     1
2  1643045               Bochum       Mainz 05     1
3  1643043  Borussia M.Gladbach     Hoffenheim     1
4  1643041         Union Berlin  Hertha Berlin     1

Finished games: 306

In [5]:
ws = sd.WhoScored(
    leagues=LEAGUE,
    seasons=SEASON_YEAR,
    headless=True,
    path_to_browser=CHROME_PATH,
    no_cache=False,
)

def mongo_finished_schedule(self, force_cache=False):
    return pd.DataFrame({
        "league": LEAGUE,
        "season": SEASON_SHORT,
        "game": finished_games["game_id"].map(lambda x: f"match_{int(x)}"),
        "game_id": finished_games["game_id"].astype(int),
    })

ws.read_schedule = types.MethodType(mongo_finished_schedule, ws)

print("WhoScored reader ready")

[07/23/26 22:46:04] INFO     Saving cached data to /Users/mario_omescu/soccerdata/data/WhoScored     ]8;id=5614489;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=5614490;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

[07/23/26 22:46:05] INFO     patching driver executable /Users/mario_omescu/Library/Application      ]8;id=5614495;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/undetected_chromedriver/patcher.py\patcher.py]8;;\:]8;id=5614496;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/undetected_chromedriver/patcher.py#346\346]8;;\
                             Support/undetected_chromedriver/undetected_chromedriver

[07/23/26 22:46:07] INFO     setting properties for headless                                        ]8;id=5614501;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/undetected_chromedriver/__init__.py\__init__.py]8;;\:]8;id=5614502;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/undetected_chromedriver/__init__.py#493\493]8;;\

WhoScored reader ready

## Extract lineups

In [ ]:
LIMIT = None 
LIVE = False
RETRY_MISSING = True


def process_game_lineups(df_players: pd.DataFrame, game_id: int, available_teams: pd.DataFrame) -> pd.DataFrame:
    
    available_teams_df = available_teams.copy()
    available_teams_df.rename(columns={'ws_team_id': 'team_id', "ws_team_name": "team_name"}, inplace=True)

    df = df_players.copy()
    df = df.rename(columns={
        "is_starter": "starting_lineup",
    })

    df["game_id"] = int(game_id)
    df["season"] = SEASON_YEAR
    df["competition_name"] = COMPETITION_NAME
    df["competition_country"] = COMPETITION_COUNTRY

    for col in ["game_id", "team_id", "player_id", "minutes_played", "jersey_number"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")

    if "starting_lineup" in df.columns:
        df["starting_lineup"] = df["starting_lineup"].fillna(False).astype(bool)

    metadata_cols = [
        "game_id", "game_date", "week", "home_team_id", "home_team_name",
        "away_team_id", "away_team_name",
    ]
    metadata = finished_games[finished_games["game_id"].eq(int(game_id))][metadata_cols].drop_duplicates("game_id")
    df = df.merge(metadata, on="game_id", how="left")

    df["played"] = pd.to_numeric(df["minutes_played"], errors="coerce").fillna(0).gt(0)
    df["game_venue"] = df["team_id"].eq(df["home_team_id"]).map({True: "home", False: "away"})
    
    df = df.merge(available_teams_df, on='team_id', how='left')
    ordered = [
        "game_id", "game_date", "season", "week", "competition_name", "competition_country",
        "team_id", "team_name", "player_id", "player_name", "starting_lineup", "minutes_played",
        "jersey_number", "starting_position", "played", "game_venue"
    ]
    return df[[c for c in ordered if c in df.columns]]


lineup_frames = []
errors = []
game_ids = finished_games["game_id"].astype(int).tolist()
if LIMIT is not None:
    game_ids = game_ids[:LIMIT]

game_ids = [1643289]

for i, game_id in enumerate(game_ids, start=1):
    try:
        print(f"[{i}/{len(game_ids)}] Extracting players for game_id={game_id}")
        loader = ws.read_events(
            match_id=game_id,
            output_fmt="loader",
            retry_missing=RETRY_MISSING,
            live=LIVE,
            on_error="skip",
        )
        df_players = loader.players(game_id=game_id)
        lineup_frames.append(process_game_lineups(df_players, game_id, available_teams))
    except Exception as exc:
        logger.exception("Failed extracting players for game_id=%s", game_id)
        errors.append({"game_id": game_id, "error": repr(exc)})

df_lineups = pd.concat(lineup_frames, ignore_index=True) if lineup_frames else pd.DataFrame()
df_errors = pd.DataFrame(errors)

print(f"Lineup rows: {len(df_lineups)}")
print(f"Failed games: {len(df_errors)}")
display(df_lineups.head())
display(df_errors.head())

[1/1] Extracting players for game_id=1643289

[07/23/26 22:46:11] INFO     [1/1] Retrieving game with id=1643289                                 ]8;id=5614509;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614510;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    ERROR    Failed extracting players for game_id=1643289                          ]8;id=5614517;file:///var/folders/jq/njqvkrp55b3g2fzq0k92__q80000gn/T/ipykernel_43484/313527250.py\313527250.py]8;;\:]8;id=5614518;file:///var/folders/jq/njqvkrp55b3g2fzq0k92__q80000gn/T/ipykernel_43484/313527250.py#68\68]8;;\
                             Traceback (most recent call last):
                               File
                             "/var/folders/jq/njqvkrp55b3g2fzq0k92__q80000gn/T/ipykernel_43484/3135
                             27250.py", line 65, in <module>
                                 df_players = loader.players(game_id=game_id)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "/opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/pytho
                             n3.11/site-packages/socceraction/data/opta/loader.py", line 427, in
                             players
                                 _deepupdate(data, parser.extract_players())
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "/opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/pytho
                             n3.11/site-packages/socceraction/data/opta/parsers/whoscored.py", line
                             162, in extract_players
                                 player_gamestats = self.extract_playergamestats()
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "/opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/pytho
                             n3.11/site-packages/socceraction/data/opta/parsers/whoscored.py", line
                             362, in extract_playergamestats
                                 for team in [self.root["home"], self.root["away"]]:
                                              ~~~~~~~~~^^^^^^^^
                             TypeError: 'NoneType' object is not subscriptable

Lineup rows: 0
Failed games: 1

Empty DataFrame
Columns: []
Index: []

   game_id                                              error
0  1643289  TypeError("'NoneType' object is not subscripta...

In [8]:
loader = ws.read_events(
            match_id=game_id,
            output_fmt="loader",
            retry_missing=RETRY_MISSING,
            live=LIVE,
            on_error="skip",
        )

[07/24/26 22:55:41] INFO     [1/1] Retrieving game with id=1643289                                 ]8;id=5614523;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614524;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

In [11]:
ws = sd.WhoScored(leagues="GER-Bundesliga", seasons=2223)
print(ws.__doc__)

[07/24/26 22:57:22] INFO     Saving cached data to /Users/mario_omescu/soccerdata/data/WhoScored     ]8;id=5614529;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=5614530;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/_common.py#250\250]8;;\

[07/24/26 22:57:23] INFO     patching driver executable /Users/mario_omescu/Library/Application      ]8;id=5614535;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/undetected_chromedriver/patcher.py\patcher.py]8;;\:]8;id=5614536;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/undetected_chromedriver/patcher.py#346\346]8;;\
                             Support/undetected_chromedriver/undetected_chromedriver

Provides pd.DataFrames from data available at http://whoscored.com.

    Data will be downloaded as necessary and cached locally in
    ``~/soccerdata/data/WhoScored``.

    Parameters
    ----------
    leagues : string or iterable, optional
        IDs of Leagues to include.
    seasons : string, int or list, optional
        Seasons to include. Supports multiple formats.
        Examples: '16-17'; 2016; '2016-17'; [14, 15, 16]
    proxy : 'tor' or or dict or list(dict) or callable, optional
        Use a proxy to hide your IP address. Valid options are:
            - "tor": Uses the Tor network. Tor should be running in
              the background on port 9050.
            - str: The address of the proxy server to use.
            - list(str): A list of proxies to choose from. A different proxy will
              be selected from this list after failed requests, allowing rotating
              proxies.
            - callable: A function that returns a valid proxy. This function will
              be called after failed requests, allowing rotating proxies.
    no_cache : bool
        If True, will not use cached data.
    no_store : bool
        If True, will not store downloaded data.
    data_dir : Path
        Path to directory where data will be cached.
    path_to_browser : Path, optional
        Path to the Chrome executable.
    headless : bool, default: True
        If True, will run Chrome in headless mode. Setting this to False might
        help to avoid getting blocked. Only supported for Selenium <4.13.

In [12]:
loader = ws.read_events(output_fmt="loader")

[07/24/26 22:57:50] INFO     Retrieving calendar for GER-Bundesliga 2223                           ]8;id=5614542;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614543;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#366\366]8;;\

                    INFO     [1/9] Retrieving fixtures for GER-Bundesliga 2223                     ]8;id=5614549;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614550;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#397\397]8;;\

                    INFO     [2/9] Retrieving fixtures for GER-Bundesliga 2223                     ]8;id=5614555;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614556;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#397\397]8;;\

                    INFO     [3/9] Retrieving fixtures for GER-Bundesliga 2223                     ]8;id=5614561;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614562;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#397\397]8;;\

                    INFO     [4/9] Retrieving fixtures for GER-Bundesliga 2223                     ]8;id=5614567;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614568;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#397\397]8;;\

                    INFO     [5/9] Retrieving fixtures for GER-Bundesliga 2223                     ]8;id=5614573;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614574;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#397\397]8;;\

                    INFO     [6/9] Retrieving fixtures for GER-Bundesliga 2223                     ]8;id=5614579;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614580;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#397\397]8;;\

                    INFO     [7/9] Retrieving fixtures for GER-Bundesliga 2223                     ]8;id=5614585;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614586;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#397\397]8;;\

                    INFO     [8/9] Retrieving fixtures for GER-Bundesliga 2223                     ]8;id=5614591;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614592;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#397\397]8;;\

                    INFO     [9/9] Retrieving fixtures for GER-Bundesliga 2223                     ]8;id=5614597;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614598;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#397\397]8;;\

                    INFO     [1/306] Retrieving game with id=1643170                               ]8;id=5614603;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614604;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [2/306] Retrieving game with id=1643160                               ]8;id=5614609;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614610;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [3/306] Retrieving game with id=1643329                               ]8;id=5614615;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614616;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [4/306] Retrieving game with id=1643200                               ]8;id=5614621;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614622;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [5/306] Retrieving game with id=1643082                               ]8;id=5614627;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614628;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [6/306] Retrieving game with id=1643214                               ]8;id=5614633;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614634;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

[07/24/26 22:58:00] WARNING  No events found for game 1643214                                      ]8;id=5614640;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614641;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#763\763]8;;\

                    INFO     [7/306] Retrieving game with id=1643155                               ]8;id=5614646;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614647;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [8/306] Retrieving game with id=1643332                               ]8;id=5614652;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614653;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [9/306] Retrieving game with id=1643119                               ]8;id=5614658;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614659;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [10/306] Retrieving game with id=1643089                              ]8;id=5614664;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614665;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [11/306] Retrieving game with id=1643125                              ]8;id=5614670;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614671;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [12/306] Retrieving game with id=1643338                              ]8;id=5614676;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614677;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [13/306] Retrieving game with id=1643129                              ]8;id=5614682;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614683;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [14/306] Retrieving game with id=1643173                              ]8;id=5614688;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614689;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [15/306] Retrieving game with id=1643263                              ]8;id=5614694;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614695;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [16/306] Retrieving game with id=1643248                              ]8;id=5614700;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614701;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [17/306] Retrieving game with id=1643123                              ]8;id=5614706;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614707;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [18/306] Retrieving game with id=1643249                              ]8;id=5614712;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614713;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [19/306] Retrieving game with id=1643102                              ]8;id=5614718;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614719;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [20/306] Retrieving game with id=1643256                              ]8;id=5614724;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614725;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [21/306] Retrieving game with id=1643267                              ]8;id=5614730;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614731;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [22/306] Retrieving game with id=1643182                              ]8;id=5614736;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614737;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [23/306] Retrieving game with id=1643052                              ]8;id=5614742;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614743;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [24/306] Retrieving game with id=1643290                              ]8;id=5614748;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614749;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [25/306] Retrieving game with id=1643075                              ]8;id=5614754;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614755;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [26/306] Retrieving game with id=1643334                              ]8;id=5614760;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614761;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [27/306] Retrieving game with id=1643097                              ]8;id=5614766;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614767;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

[07/24/26 22:58:09] WARNING  No events found for game 1643097                                      ]8;id=5614772;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614773;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#763\763]8;;\

                    INFO     [28/306] Retrieving game with id=1643237                              ]8;id=5614778;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614779;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [29/306] Retrieving game with id=1643044                              ]8;id=5614784;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614785;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [30/306] Retrieving game with id=1643300                              ]8;id=5614790;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614791;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [31/306] Retrieving game with id=1643193                              ]8;id=5614796;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614797;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [32/306] Retrieving game with id=1643313                              ]8;id=5614802;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614803;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [33/306] Retrieving game with id=1643276                              ]8;id=5614808;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614809;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [34/306] Retrieving game with id=1643236                              ]8;id=5614814;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614815;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [35/306] Retrieving game with id=1643180                              ]8;id=5614820;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614821;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [36/306] Retrieving game with id=1643187                              ]8;id=5614826;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614827;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [37/306] Retrieving game with id=1643257                              ]8;id=5614832;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614833;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [38/306] Retrieving game with id=1643331                              ]8;id=5614838;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614839;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [39/306] Retrieving game with id=1643336                              ]8;id=5614844;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614845;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [40/306] Retrieving game with id=1643085                              ]8;id=5614850;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614851;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [41/306] Retrieving game with id=1643130                              ]8;id=5614856;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614857;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [42/306] Retrieving game with id=1643201                              ]8;id=5614862;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614863;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [43/306] Retrieving game with id=1643281                              ]8;id=5614868;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614869;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [44/306] Retrieving game with id=1643217                              ]8;id=5614874;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614875;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [45/306] Retrieving game with id=1643100                              ]8;id=5614880;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614881;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [46/306] Retrieving game with id=1643121                              ]8;id=5614886;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614887;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [47/306] Retrieving game with id=1643233                              ]8;id=5614892;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614893;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [48/306] Retrieving game with id=1643299                              ]8;id=5614898;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614899;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [49/306] Retrieving game with id=1643223                              ]8;id=5614904;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614905;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [50/306] Retrieving game with id=1643318                              ]8;id=5614910;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614911;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [51/306] Retrieving game with id=1643317                              ]8;id=5614916;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614917;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [52/306] Retrieving game with id=1643168                              ]8;id=5614922;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614923;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [53/306] Retrieving game with id=1643077                              ]8;id=5614928;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614929;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [54/306] Retrieving game with id=1643049                              ]8;id=5614934;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614935;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [55/306] Retrieving game with id=1643112                              ]8;id=5614940;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614941;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [56/306] Retrieving game with id=1643258                              ]8;id=5614946;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614947;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [57/306] Retrieving game with id=1643316                              ]8;id=5614952;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614953;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [58/306] Retrieving game with id=1643158                              ]8;id=5614958;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614959;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [59/306] Retrieving game with id=1643211                              ]8;id=5614964;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614965;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [60/306] Retrieving game with id=1643174                              ]8;id=5614970;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614971;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [61/306] Retrieving game with id=1643148                              ]8;id=5614976;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614977;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [62/306] Retrieving game with id=1643283                              ]8;id=5614982;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614983;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [63/306] Retrieving game with id=1643279                              ]8;id=5614988;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614989;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [64/306] Retrieving game with id=1643226                              ]8;id=5614994;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5614995;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [65/306] Retrieving game with id=1643235                              ]8;id=5615000;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615001;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [66/306] Retrieving game with id=1643092                              ]8;id=5615006;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615007;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [67/306] Retrieving game with id=1643043                              ]8;id=5615012;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615013;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [68/306] Retrieving game with id=1643047                              ]8;id=5615018;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615019;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [69/306] Retrieving game with id=1643303                              ]8;id=5615024;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615025;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [70/306] Retrieving game with id=1643293                              ]8;id=5615030;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615031;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [71/306] Retrieving game with id=1643221                              ]8;id=5615036;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615037;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [72/306] Retrieving game with id=1643309                              ]8;id=5615042;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615043;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [73/306] Retrieving game with id=1643136                              ]8;id=5615048;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615049;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [74/306] Retrieving game with id=1643109                              ]8;id=5615054;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615055;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [75/306] Retrieving game with id=1643342                              ]8;id=5615060;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615061;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [76/306] Retrieving game with id=1643142                              ]8;id=5615066;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615067;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [77/306] Retrieving game with id=1643273                              ]8;id=5615072;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615073;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [78/306] Retrieving game with id=1643328                              ]8;id=5615078;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615079;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [79/306] Retrieving game with id=1643344                              ]8;id=5615084;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615085;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [80/306] Retrieving game with id=1643157                              ]8;id=5615090;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615091;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [81/306] Retrieving game with id=1643222                              ]8;id=5615096;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615097;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [82/306] Retrieving game with id=1643178                              ]8;id=5615102;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615103;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [83/306] Retrieving game with id=1643220                              ]8;id=5615108;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615109;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [84/306] Retrieving game with id=1643252                              ]8;id=5615114;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615115;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [85/306] Retrieving game with id=1643055                              ]8;id=5615120;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615121;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [86/306] Retrieving game with id=1643143                              ]8;id=5615126;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615127;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

[07/24/26 22:58:10] INFO     [87/306] Retrieving game with id=1643166                              ]8;id=5615132;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615133;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [88/306] Retrieving game with id=1643135                              ]8;id=5615138;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615139;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [89/306] Retrieving game with id=1643203                              ]8;id=5615144;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615145;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [90/306] Retrieving game with id=1643274                              ]8;id=5615150;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615151;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [91/306] Retrieving game with id=1643147                              ]8;id=5615156;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615157;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [92/306] Retrieving game with id=1643282                              ]8;id=5615162;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615163;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [93/306] Retrieving game with id=1643280                              ]8;id=5615168;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615169;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [94/306] Retrieving game with id=1643234                              ]8;id=5615174;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615175;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [95/306] Retrieving game with id=1643253                              ]8;id=5615180;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615181;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [96/306] Retrieving game with id=1643310                              ]8;id=5615186;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615187;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [97/306] Retrieving game with id=1643101                              ]8;id=5615192;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615193;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [98/306] Retrieving game with id=1643272                              ]8;id=5615198;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615199;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [99/306] Retrieving game with id=1643141                              ]8;id=5615204;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615205;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [100/306] Retrieving game with id=1643297                             ]8;id=5615210;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615211;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [101/306] Retrieving game with id=1643078                             ]8;id=5615216;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615217;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [102/306] Retrieving game with id=1643213                             ]8;id=5615222;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615223;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [103/306] Retrieving game with id=1643165                             ]8;id=5615228;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615229;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [104/306] Retrieving game with id=1643050                             ]8;id=5615234;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615235;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [105/306] Retrieving game with id=1643159                             ]8;id=5615240;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615241;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [106/306] Retrieving game with id=1643185                             ]8;id=5615246;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615247;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [107/306] Retrieving game with id=1643259                             ]8;id=5615252;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615253;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [108/306] Retrieving game with id=1643114                             ]8;id=5615258;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615259;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [109/306] Retrieving game with id=1643247                             ]8;id=5615264;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615265;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [110/306] Retrieving game with id=1643261                             ]8;id=5615270;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615271;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [111/306] Retrieving game with id=1643117                             ]8;id=5615276;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615277;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [112/306] Retrieving game with id=1643232                             ]8;id=5615282;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615283;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [113/306] Retrieving game with id=1643088                             ]8;id=5615288;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615289;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [114/306] Retrieving game with id=1643169                             ]8;id=5615294;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615295;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [115/306] Retrieving game with id=1643134                             ]8;id=5615300;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615301;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [116/306] Retrieving game with id=1643063                             ]8;id=5615306;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615307;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [117/306] Retrieving game with id=1643040                             ]8;id=5615312;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615313;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [118/306] Retrieving game with id=1643339                             ]8;id=5615318;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615319;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [119/306] Retrieving game with id=1643340                             ]8;id=5615324;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615325;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [120/306] Retrieving game with id=1643164                             ]8;id=5615330;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615331;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [121/306] Retrieving game with id=1643084                             ]8;id=5615336;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615337;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [122/306] Retrieving game with id=1643314                             ]8;id=5615342;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615343;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [123/306] Retrieving game with id=1643206                             ]8;id=5615348;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615349;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [124/306] Retrieving game with id=1643061                             ]8;id=5615354;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615355;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [125/306] Retrieving game with id=1643059                             ]8;id=5615360;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615361;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [126/306] Retrieving game with id=1643251                             ]8;id=5615366;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615367;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [127/306] Retrieving game with id=1643122                             ]8;id=5615372;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615373;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [128/306] Retrieving game with id=1643254                             ]8;id=5615378;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615379;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [129/306] Retrieving game with id=1643196                             ]8;id=5615384;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615385;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [130/306] Retrieving game with id=1643227                             ]8;id=5615390;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615391;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [131/306] Retrieving game with id=1643298                             ]8;id=5615396;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615397;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [132/306] Retrieving game with id=1643216                             ]8;id=5615402;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615403;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [133/306] Retrieving game with id=1643128                             ]8;id=5615408;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615409;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [134/306] Retrieving game with id=1643245                             ]8;id=5615414;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615415;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [135/306] Retrieving game with id=1643072                             ]8;id=5615420;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615421;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [136/306] Retrieving game with id=1643286                             ]8;id=5615426;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615427;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [137/306] Retrieving game with id=1643277                             ]8;id=5615432;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615433;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [138/306] Retrieving game with id=1643150                             ]8;id=5615438;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615439;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [139/306] Retrieving game with id=1643326                             ]8;id=5615444;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615445;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [140/306] Retrieving game with id=1643062                             ]8;id=5615450;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615451;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [141/306] Retrieving game with id=1643255                             ]8;id=5615456;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615457;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [142/306] Retrieving game with id=1643177                             ]8;id=5615462;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615463;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [143/306] Retrieving game with id=1643244                             ]8;id=5615468;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615469;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [144/306] Retrieving game with id=1643238                             ]8;id=5615474;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615475;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [145/306] Retrieving game with id=1643045                             ]8;id=5615480;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615481;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [146/306] Retrieving game with id=1643231                             ]8;id=5615486;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615487;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [147/306] Retrieving game with id=1643039                             ]8;id=5615492;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615493;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [148/306] Retrieving game with id=1643107                             ]8;id=5615498;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615499;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [149/306] Retrieving game with id=1643264                             ]8;id=5615504;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615505;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

[07/24/26 22:58:11] INFO     [150/306] Retrieving game with id=1643175                             ]8;id=5615510;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615511;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [151/306] Retrieving game with id=1643099                             ]8;id=5615516;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615517;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [152/306] Retrieving game with id=1643306                             ]8;id=5615522;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615523;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [153/306] Retrieving game with id=1643315                             ]8;id=5615528;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615529;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [154/306] Retrieving game with id=1643327                             ]8;id=5615534;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615535;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [155/306] Retrieving game with id=1643048                             ]8;id=5615540;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615541;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [156/306] Retrieving game with id=1643325                             ]8;id=5615546;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615547;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [157/306] Retrieving game with id=1643064                             ]8;id=5615552;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615553;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [158/306] Retrieving game with id=1643224                             ]8;id=5615558;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615559;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [159/306] Retrieving game with id=1643090                             ]8;id=5615564;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615565;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [160/306] Retrieving game with id=1643172                             ]8;id=5615570;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615571;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [161/306] Retrieving game with id=1643071                             ]8;id=5615576;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615577;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [162/306] Retrieving game with id=1643268                             ]8;id=5615582;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615583;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [163/306] Retrieving game with id=1643284                             ]8;id=5615588;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615589;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [164/306] Retrieving game with id=1643079                             ]8;id=5615594;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615595;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [165/306] Retrieving game with id=1643149                             ]8;id=5615600;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615601;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [166/306] Retrieving game with id=1643312                             ]8;id=5615606;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615607;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [167/306] Retrieving game with id=1643105                             ]8;id=5615612;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615613;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [168/306] Retrieving game with id=1643133                             ]8;id=5615618;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615619;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [169/306] Retrieving game with id=1643191                             ]8;id=5615624;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615625;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [170/306] Retrieving game with id=1643323                             ]8;id=5615630;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615631;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [171/306] Retrieving game with id=1643324                             ]8;id=5615636;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615637;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [172/306] Retrieving game with id=1643192                             ]8;id=5615642;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615643;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [173/306] Retrieving game with id=1643239                             ]8;id=5615648;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615649;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [174/306] Retrieving game with id=1643304                             ]8;id=5615654;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615655;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [175/306] Retrieving game with id=1643140                             ]8;id=5615660;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615661;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [176/306] Retrieving game with id=1643153                             ]8;id=5615666;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615667;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [177/306] Retrieving game with id=1643162                             ]8;id=5615672;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615673;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [178/306] Retrieving game with id=1643104                             ]8;id=5615678;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615679;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [179/306] Retrieving game with id=1643205                             ]8;id=5615684;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615685;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [180/306] Retrieving game with id=1643271                             ]8;id=5615690;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615691;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [181/306] Retrieving game with id=1643294                             ]8;id=5615696;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615697;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [182/306] Retrieving game with id=1643171                             ]8;id=5615702;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615703;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [183/306] Retrieving game with id=1643108                             ]8;id=5615708;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615709;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [184/306] Retrieving game with id=1643266                             ]8;id=5615714;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615715;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [185/306] Retrieving game with id=1643183                             ]8;id=5615720;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615721;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [186/306] Retrieving game with id=1643250                             ]8;id=5615726;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615727;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [187/306] Retrieving game with id=1643091                             ]8;id=5615732;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615733;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [188/306] Retrieving game with id=1643131                             ]8;id=5615738;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615739;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [189/306] Retrieving game with id=1643161                             ]8;id=5615744;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615745;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [190/306] Retrieving game with id=1643073                             ]8;id=5615750;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615751;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [191/306] Retrieving game with id=1643291                             ]8;id=5615756;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615757;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [192/306] Retrieving game with id=1643068                             ]8;id=5615762;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615763;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [193/306] Retrieving game with id=1643181                             ]8;id=5615768;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615769;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [194/306] Retrieving game with id=1643270                             ]8;id=5615774;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615775;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [195/306] Retrieving game with id=1643154                             ]8;id=5615780;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615781;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [196/306] Retrieving game with id=1643320                             ]8;id=5615786;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615787;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [197/306] Retrieving game with id=1643145                             ]8;id=5615792;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615793;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [198/306] Retrieving game with id=1643186                             ]8;id=5615798;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615799;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [199/306] Retrieving game with id=1643067                             ]8;id=5615804;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615805;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [200/306] Retrieving game with id=1643219                             ]8;id=5615810;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615811;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [201/306] Retrieving game with id=1643083                             ]8;id=5615816;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615817;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [202/306] Retrieving game with id=1643137                             ]8;id=5615822;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615823;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [203/306] Retrieving game with id=1643126                             ]8;id=5615828;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615829;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [204/306] Retrieving game with id=1643106                             ]8;id=5615834;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615835;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [205/306] Retrieving game with id=1643228                             ]8;id=5615840;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615841;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [206/306] Retrieving game with id=1643139                             ]8;id=5615846;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615847;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [207/306] Retrieving game with id=1643189                             ]8;id=5615852;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615853;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [208/306] Retrieving game with id=1643057                             ]8;id=5615858;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615859;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [209/306] Retrieving game with id=1643246                             ]8;id=5615864;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615865;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [210/306] Retrieving game with id=1643330                             ]8;id=5615870;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615871;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

[07/24/26 22:58:12] INFO     [211/306] Retrieving game with id=1643081                             ]8;id=5615876;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615877;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [212/306] Retrieving game with id=1643060                             ]8;id=5615882;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615883;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [213/306] Retrieving game with id=1643197                             ]8;id=5615888;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615889;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [214/306] Retrieving game with id=1643070                             ]8;id=5615894;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615895;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [215/306] Retrieving game with id=1643069                             ]8;id=5615900;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615901;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [216/306] Retrieving game with id=1643202                             ]8;id=5615906;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615907;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [217/306] Retrieving game with id=1643042                             ]8;id=5615912;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615913;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [218/306] Retrieving game with id=1643207                             ]8;id=5615918;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615919;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [219/306] Retrieving game with id=1643113                             ]8;id=5615924;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615925;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [220/306] Retrieving game with id=1643053                             ]8;id=5615930;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615931;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [221/306] Retrieving game with id=1643096                             ]8;id=5615936;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615937;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [222/306] Retrieving game with id=1643152                             ]8;id=5615942;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615943;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [223/306] Retrieving game with id=1643240                             ]8;id=5615948;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615949;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [224/306] Retrieving game with id=1643093                             ]8;id=5615954;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615955;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [225/306] Retrieving game with id=1643080                             ]8;id=5615960;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615961;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [226/306] Retrieving game with id=1643322                             ]8;id=5615966;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615967;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [227/306] Retrieving game with id=1643199                             ]8;id=5615972;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615973;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [228/306] Retrieving game with id=1643210                             ]8;id=5615978;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615979;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [229/306] Retrieving game with id=1643209                             ]8;id=5615984;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615985;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [230/306] Retrieving game with id=1643243                             ]8;id=5615990;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615991;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [231/306] Retrieving game with id=1643146                             ]8;id=5615996;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5615997;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [232/306] Retrieving game with id=1643208                             ]8;id=5616002;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616003;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [233/306] Retrieving game with id=1643116                             ]8;id=5616008;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616009;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [234/306] Retrieving game with id=1643269                             ]8;id=5616014;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616015;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [235/306] Retrieving game with id=1643086                             ]8;id=5616020;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616021;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [236/306] Retrieving game with id=1643195                             ]8;id=5616026;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616027;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [237/306] Retrieving game with id=1643345                             ]8;id=5616032;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616033;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [238/306] Retrieving game with id=1643321                             ]8;id=5616038;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616039;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [239/306] Retrieving game with id=1643262                             ]8;id=5616044;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616045;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [240/306] Retrieving game with id=1643094                             ]8;id=5616050;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616051;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [241/306] Retrieving game with id=1643288                             ]8;id=5616056;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616057;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [242/306] Retrieving game with id=1643144                             ]8;id=5616062;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616063;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [243/306] Retrieving game with id=1643265                             ]8;id=5616068;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616069;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [244/306] Retrieving game with id=1643120                             ]8;id=5616074;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616075;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [245/306] Retrieving game with id=1643167                             ]8;id=5616080;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616081;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [246/306] Retrieving game with id=1643176                             ]8;id=5616086;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616087;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [247/306] Retrieving game with id=1643230                             ]8;id=5616092;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616093;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [248/306] Retrieving game with id=1643333                             ]8;id=5616098;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616099;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [249/306] Retrieving game with id=1643151                             ]8;id=5616104;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616105;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [250/306] Retrieving game with id=1643225                             ]8;id=5616110;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616111;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [251/306] Retrieving game with id=1643054                             ]8;id=5616116;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616117;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [252/306] Retrieving game with id=1643335                             ]8;id=5616122;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616123;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [253/306] Retrieving game with id=1643065                             ]8;id=5616128;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616129;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [254/306] Retrieving game with id=1643305                             ]8;id=5616134;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616135;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [255/306] Retrieving game with id=1643087                             ]8;id=5616140;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616141;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [256/306] Retrieving game with id=1643103                             ]8;id=5616146;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616147;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [257/306] Retrieving game with id=1643051                             ]8;id=5616152;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616153;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [258/306] Retrieving game with id=1643319                             ]8;id=5616158;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616159;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [259/306] Retrieving game with id=1643311                             ]8;id=5616164;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616165;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [260/306] Retrieving game with id=1643188                             ]8;id=5616170;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616171;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [261/306] Retrieving game with id=1643156                             ]8;id=5616176;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616177;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [262/306] Retrieving game with id=1643115                             ]8;id=5616182;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616183;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [263/306] Retrieving game with id=1643307                             ]8;id=5616188;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616189;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [264/306] Retrieving game with id=1643076                             ]8;id=5616194;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616195;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [265/306] Retrieving game with id=1643041                             ]8;id=5616200;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616201;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [266/306] Retrieving game with id=1643296                             ]8;id=5616206;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616207;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [267/306] Retrieving game with id=1643287                             ]8;id=5616212;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616213;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [268/306] Retrieving game with id=1643118                             ]8;id=5616218;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616219;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [269/306] Retrieving game with id=1643056                             ]8;id=5616224;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616225;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [270/306] Retrieving game with id=1643295                             ]8;id=5616230;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616231;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [271/306] Retrieving game with id=1643289                             ]8;id=5616236;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616237;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [272/306] Retrieving game with id=1643212                             ]8;id=5616242;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616243;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [273/306] Retrieving game with id=1643337                             ]8;id=5616248;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616249;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

[07/24/26 22:58:13] INFO     [274/306] Retrieving game with id=1643046                             ]8;id=5616254;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616255;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [275/306] Retrieving game with id=1643204                             ]8;id=5616260;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616261;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [276/306] Retrieving game with id=1643138                             ]8;id=5616266;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616267;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [277/306] Retrieving game with id=1643058                             ]8;id=5616272;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616273;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [278/306] Retrieving game with id=1643127                             ]8;id=5616278;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616279;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [279/306] Retrieving game with id=1643074                             ]8;id=5616284;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616285;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [280/306] Retrieving game with id=1643302                             ]8;id=5616290;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616291;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [281/306] Retrieving game with id=1643275                             ]8;id=5616296;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616297;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [282/306] Retrieving game with id=1643260                             ]8;id=5616302;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616303;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [283/306] Retrieving game with id=1643285                             ]8;id=5616308;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616309;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [284/306] Retrieving game with id=1643242                             ]8;id=5616314;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616315;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [285/306] Retrieving game with id=1643110                             ]8;id=5616320;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616321;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [286/306] Retrieving game with id=1643341                             ]8;id=5616326;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616327;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [287/306] Retrieving game with id=1643198                             ]8;id=5616332;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616333;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [288/306] Retrieving game with id=1643179                             ]8;id=5616338;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616339;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [289/306] Retrieving game with id=1643292                             ]8;id=5616344;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616345;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [290/306] Retrieving game with id=1643163                             ]8;id=5616350;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616351;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [291/306] Retrieving game with id=1643278                             ]8;id=5616356;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616357;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [292/306] Retrieving game with id=1643095                             ]8;id=5616362;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616363;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [293/306] Retrieving game with id=1643098                             ]8;id=5616368;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616369;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [294/306] Retrieving game with id=1643111                             ]8;id=5616374;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616375;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [295/306] Retrieving game with id=1643229                             ]8;id=5616380;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616381;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [296/306] Retrieving game with id=1643066                             ]8;id=5616386;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616387;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [297/306] Retrieving game with id=1643241                             ]8;id=5616392;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616393;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [298/306] Retrieving game with id=1643218                             ]8;id=5616398;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616399;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [299/306] Retrieving game with id=1643301                             ]8;id=5616404;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616405;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [300/306] Retrieving game with id=1643124                             ]8;id=5616410;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616411;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [301/306] Retrieving game with id=1643215                             ]8;id=5616416;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616417;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [302/306] Retrieving game with id=1643308                             ]8;id=5616422;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616423;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [303/306] Retrieving game with id=1643190                             ]8;id=5616428;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616429;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [304/306] Retrieving game with id=1643132                             ]8;id=5616434;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616435;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [305/306] Retrieving game with id=1643194                             ]8;id=5616440;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616441;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

                    INFO     [306/306] Retrieving game with id=1643184                             ]8;id=5616446;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py\whoscored.py]8;;\:]8;id=5616447;file:///opt/homebrew/Caskroom/miniconda/base/envs/sports_analytics/lib/python3.11/site-packages/soccerdata/whoscored.py#689\689]8;;\

In [14]:
df_players = loader.players(game_id=1643229)

In [15]:
df_players

,game_id,team_id,player_id,player_name,is_starter,minutes_played,jersey_number,starting_position
0,1643229,7614,39187,Ørjan Nyland,True,98,13,GK
1,1643229,7614,372855,Mohamed Simakan,True,98,2,DR
2,1643229,7614,143600,Lukas Klostermann,True,98,16,DC
3,1643229,7614,104917,Willi Orbán,True,98,4,DC
4,1643229,7614,115161,Marcel Halstenberg,True,63,23,DL
5,1643229,7614,248010,Konrad Laimer,True,63,27,DMC
6,1643229,7614,298837,Amadou Haidara,True,48,8,DMC
7,1643229,7614,261212,Dani Olmo,True,98,7,AMC
8,1643229,7614,141716,Emil Forsberg,True,70,10,AMC
9,1643229,7614,300945,Christopher Nkunku,True,98,18,FW
10,1643229,7614,130903,Timo Werner,True,63,11,FW
11,1643229,7614,262856,Xaver Schlager,False,35,24,Sub
12,1643229,7614,132943,Yussuf Poulsen,False,35,9,Sub
13,1643229,7614,330538,David Raum,False,35,22,Sub
14,1643229,7614,369875,Dominik Szoboszlai,False,28,17,Sub
15,1643229,7614,80994,Kevin Kampl,False,50,44,Sub
16,1643229,7614,296769,Benjamin Henrichs,False,0,39,Sub
17,1643229,7614,104885,Janis Blaswich,False,0,21,Sub
18,1643229,7614,299460,André Silva,False,0,19,Sub
19,1643229,7614,248112,Abdou Diallo,False,0,37,Sub
20,1643229,39,23592,Ralf Fährmann,True,98,1,GK
21,1643229,39,131049,Cédric Brunner,True,98,27,DR
22,1643229,39,351705,Sepp van den Berg,True,98,5,DC
23,1643229,39,82628,Marcin Kaminski,True,98,35,DC
24,1643229,39,415931,Henning Matriciani,True,72,41,DL
25,1643229,39,369861,Alex Král,True,98,30,DMC
26,1643229,39,70227,Danny Latza,True,77,8,DMC
27,1643229,39,401251,Rodrigo Zalazar,True,58,10,AMR
28,1643229,39,83804,Dominick Drexler,True,98,24,AMC
29,1643229,39,361419,Marius Bülter,True,98,11,AML
30,1643229,39,77471,Sebastian Polter,True,98,40,FW
31,1643229,39,361300,Tobias Mohr,False,40,29,Sub
32,1643229,39,301027,Thomas Ouwejan,False,26,2,Sub
33,1643229,39,140646,Kenan Karaman,False,21,19,Sub
34,1643229,39,404216,Leo Greiml,False,0,3,Sub
35,1643229,39,401108,Niklas Tauer,False,0,21,Sub
36,1643229,39,285654,Tim Skarke,False,0,20,Sub
37,1643229,39,97743,Alexander Schwolow,False,0,13,Sub
38,1643229,39,37204,Maya Yoshida,False,0,4,Sub
39,1643229,39,110427,Michael Frey,False,0,26,Sub

In [ ]:
df_lineups['team_name'].value_counts()

In [7]:
SEASON_SHORT

'2223'